[package]
name = "ExetrixAnalysis"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
tempfile = "3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
tera = "1.17"
